# Generated by Django 3.1.1 on 2020-10-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='ava1', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='motto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[(1, 'manager'), (2, 'employee')], default=2, max_length=10),
        ),
    ]
